version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "quarterly"
    cooldown:
      default-days: 7
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: .github/cli
    schedule:
      interval: "quarterly"
    cooldown:
      default-days: 7
    groups:
      dependencies:
        patterns:
          - "*"
